### PR TITLE
Add actions to github workflow

### LINKED ISSUE #3: Hacktoberfest: Ideas for Github Actions Workflow
# Hacktoberfest 2020
 
1.  A workflow to run basic test on pull request.
2. A workflow to check against shell script analysis (e.g: https://www.shellcheck.net/) on pull request. 

Useful GitHub Actions:
* `reviewdog/action-spellcheck`

If you are interested to work on these or have new ideas, let me know in the comment and start submit the pull request.

Puru,
Happy Hacking

### PR DESCRIPTION
**Pull request by raydwaipayan**
Added three new actions to workflow:

1) Linter
2) shellcheck
3) misspellings check

Closes #3

### CODE REVIEW

**Comment by raydwaipayan** [comment]
@tuladhar Ack please!

**Review by tuladhar — CHANGES_REQUESTED** [review]
Thanks @raydwaipayan, looks good. Let's also add on push event.

**Comment by raydwaipayan** [comment]
@tuladhar Push event added to workflow!

**Review by tuladhar — APPROVED** [review]
Looks good 👍. Thanks for your contribution @raydwaipayan. Merging it.

**Pull request merged**
